open_graph:
  enable: true
  twitter_id: # for open_graph meta
article:
  type: tech # tech/story
  auto_excerpt: 200
  share: [link] # [wechat, weibo, email, link]
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: more
      theme: ""
      title: 更多
      icon: ""
      url: /more/
logo:
  avatar: "[{config.avatar}](/about/)" # you can set avatar link in _config.yml or '[https://xxx.png](/about/)'
  title: "[{config.title}](/)" # you can set html tag like: '[<img no-lazy height="32px" src="xxx"/>](/)'
  subtitle: "文字1 | 文字2" # '文字1 | 文字2' (鼠标放上去会切换到文字2)

footer:
  social:
    github:
      icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder/social/08a41b181ce68.svg"/>'
      url: https://
  content: | # 支持 Markdown 格式
    本站由 [{author.name}](/) 使用 [{theme.name} {theme.version}]({theme.tree}) 主题创建。

######## Tag Plugins ########
tag_plugins:
  # {% image %}
  image:
    fancybox: true
# 站点主结构树
site_tree:
  # -- 列表类页面 -- #
  # 主页配置
  home:
    leftbar: welcome, recent
    rightbar: timeline
  # 博客列表页配置
  index_blog:
    base_dir: blog # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 post 的页面默认使用这里配置的 menu_id
    leftbar: welcome, recent # for categories/tags/archives
    rightbar: timeline
    nav_tabs:
      # 近期发布 分类 标签 专栏 归档 and ...
      # '朋友文章': /friends/rss/
  # 博客专栏列表页配置
  index_topic:
    base_dir: topic # 只影响自动生成的页面路径
    menu_id: post # 未在 front-matter 中指定 menu_id 时，layout 为 topic 的页面默认使用这里配置的 menu_id
  # 文档列表页配置
  index_wiki:
    base_dir: wiki # 只影响自动生成的页面路径
    menu_id: wiki # 未在 front-matter 中指定 menu_id 时，layout 为 wiki 的页面默认使用这里配置的 menu_id
    leftbar: related, recent # for wiki
    rightbar: timeline
    nav_tabs:
      # 'more': https://github.com/xaoxuu
style:
  leftbar:
    background-image: url(https://w.wallhaven.cc/full/57/wallhaven-571je1.jpg)
  prefers_theme: system
  font-family:
    body: "'Zhuque Fangsong (technical preview)', system-ui, 'Microsoft Yahei', 'Segoe UI', Arial, sans-serif"
